In [2]:
# Importing the necessary packages
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

# To ensure all outputs from a cell are shown
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# To ensure all columns of a dataframe are shown
pd.set_option("display.max_columns", None)

In [3]:
# Reading in the data
df = pd.read_csv("train.csv")
df

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,churn_probability
0,0,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,31.277,87.009,7.527,48.58,124.38,1.29,32.24,96.68,2.33,0.00,0.0,0.0,0.00,0.0,0.00,2.23,0.00,0.28,5.29,16.04,2.33,0.00,0.00,0.00,0.00,0.00,0.00,7.53,16.04,2.61,46.34,124.38,1.01,18.75,80.61,0.00,0.00,0.0,0.0,0.0,0.0,0.0,65.09,204.99,1.01,0.00,0.0,0.0,8.20,0.63,0.00,0.38,0.0,0.0,81.21,221.68,3.63,2.43,3.68,7.79,0.83,21.08,16.91,0.00,0.00,0.00,3.26,24.76,24.71,0.00,7.61,0.21,7.46,19.96,14.96,0.0,0.0,0.00,0.0,0.0,0.0,7.46,27.58,15.18,11.84,53.04,40.56,0.0,0.0,0.66,0.00,0.0,0.00,1.11,0.69,0.00,3,2,2,77,65,10,65,65,10,6/22/2014,7/10/2014,8/24/2014,65,65,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1958,0.00,0.00,0.00,0
1,1,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,0.000,122.787,42.953,0.00,0.00,0.00,0.00,25.99,30.89,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22.01,29.79,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,30.73,31.66,0.00,0.0,0.0,0.00,30.73,31.66,1.68,19.09,10.53,1.41,18.68,11.09,0.35,1.66,3.40,3.44,39.44,25.03,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,3.44,39.44,25.04,0.0,0.0,0.01,0.00,0.0,0.00,0.00,0.00,0.00,3,4,5,0,145,50,0,145,50,6/12/2014,7/10/2014,8/26/2014,0,0,0,NaN,7/8/2014,NaN,NaN,1.0,NaN,NaN,145.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,145.0,NaN,0.00,352.91,0.00,0.00,3.96,0.00,NaN,122.07,NaN,NaN,122.08,NaN,NaN,0.0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,NaN,1.0,NaN,710,0.00,0.00,0.00,0
2,2,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,60.806,103.176,0.000,0.53,15.93,0.00,53.99,82.05,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.53,12.98,0.00,24.11,0.00,0.00,0.00,0.00,0.00,2.14,0.00,0.00,24.64,12.98,0.00,0.00,2.94,0.00,28.94,82.05,0.00,0.00,0.0,0.0,0.0,0.0,0.0,28.94,84.99,0.00,0.00,0.0,0.0,2.89,1.38,0.00,0.00,0.0,0.0,56.49,99.36,0.00,4.51,6.16,6.49,89.86,25.18,23.51,0.00,0.00,0.00,94.38,31.34,30.01,11.69,0.00,0.00,18.21,2.48,6.38,0.0,0.0,0.00,0.0,0.0,0.0,29.91,2.48,6.38,124.29,33.83,36.64,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.25,2,4,2,70,120,0,70,70,0,6/11/2014,7/22/2014,8/24/2014,70,50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,882,0.00,0.00,0.00,0
3,3,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,156.362,205.260,111.095,7.26,16.01,0.00,68.76,78.48,50.23,0.00,0.0,0.0,0.00,0.0,1.63,6.99,3.94,0.00,37.91,44.89,23.63,0.00,0.00,0.00,0.00,0.00,8.03,44.91,48.84,23.63,0.26,12.06,0.00,15.33,25.93,4.60,0.56,0.0,0.0,0.0,0.0,0.0,16.16,37.99,4.60,0.00,0.0,0.0,14.95,9.13,25.61,0.00,0.0,0.0,76.03,95.98,53.84,24.98,4.84,23.88,53.99,44.23,57.14,7.23,0.81,0.00,86.21,49.89,81.03,0.00,0.00,0.00,8.89,0.28,2.81,0.0,0.0,0.00,0.0,0.0,0.0,8.89,0.28,2.81,95.11,50.18,83.84,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,2,4,3,160,240,130,110,110,50,6/15/2014,7/21/2014,8/25/2014,110,110,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,982,0.00,0.00,0.00,0
4,4,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,240.708,128.191,101.565,21.28,4.83,6.13,56.99,38.11,9.63,53.64,0.0,0.0,15.73,0.0,0.00,10.16,4.83,6.13,36.74,19.88,4.61,11.99,1.23,5.01,0.00,9.85,0.00,58.91,25.94,15.76,0.00,0.00,0.00,4.35,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,4.35,0.00,0.00,0.00,0.0,0.0,0.00,17.00,0.00,0.00,0.0,0.0,63.26,42.94,15.76,5.44,1.39,2.66,10.58,4.33,19.49,5.51,3.63,6.14,21.54,9.36,28.31,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,21.54,9.36,28.31,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,13,10,8,290,136,122,50,41,30,6/25/2014,7/26/2014,8/30/2014,25,10,30,6/25/2014,7/23/2014,8/20/2014,7.0,7.0,6.0,25.0,41.0,25.0,7.0,6.0,6.0,0.0,1.0,0.0,175.0,191.0,142.0,390.80,308.89,213.47,0.00,0.00,0.00,0.00,35.00,0.00,0.00,35.12,0.00,0.0,0.0,0.0,0,0,0,7,6,6,0,0,0,0,1,0,1.0,1.0,1.0,647,0.00,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69994,69994,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,15.760,410.924,329.136,0.00,7.36,10.93,0.00,488.46,381.64,14.96,0.0,0.0,0.00,0.0,0.00,0.00,2.44,7.19,0.00,60.64,89.66,0.00,0.00,0.00,0.00,2.43,0.86,0.00,63.09,96.86,0.00,4.91,3.73,0.00,414.61,290.14,0.00,0.0,0.0,0.0,0.0,0.0,0.00,419.53,293.88,0.00,0.0,0.0,0.00,14.05,1.83,0.00,0.0,0.0,0.00,496.68,392.58,0.00,26.59,33.84,0.00,172.33,223.91,0.00,1.06,0.00,0.00,199.99,257.76,0.00,0.00,0.00,0.00,21.99,11.79,0.0,0.0,0.00,0.0,0.0,0.0,0.00,21.99,11.79,0.00,221.99,269.56,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,1,17,13,50,397,512,50,110,130,6/18/2014,7/31/2014,8/31/2014,50,20,130,NaN,7/31/2014,8/21/2014,NaN,7.0,1.0,NaN,25.0,17.0,NaN,6.0,1.0,NaN,1.0,0.0,NaN,135.0,17.0,0.00,244.59,144.31,0.00,0.00,0.00,NaN,21.91,0.00,NaN,60.61,48.00,NaN,0.0,0.0,0,0,0,0,6,1,0,0,0,0,1,0,NaN,1.0,1.0,221,0.00,0.00,0.00,0
69995,69995,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,160.083,289.129,265.772,116.54,196.46,232.63,49.53,96.28,48.06,0.00,0.0,0.0,0.00,0.0,0.00,7.18,30.11,9.06,37.53,73.84,47.34,2.01,0.00,0.00,0.00,4.01,0.00,46.73,103.96,56.41,109.36,166.34,223.56,9.98,18.41,0.53,0.00,0.0,0.0,0.0,0.0,0.0,119.34,184.76,224.09,0.00,0.0,0.0,0.13,4.01,0.18,0.00,0.0,0.0,166.21,292.74,280.69,30.48,28.48,23.09,21.78,35.18,28.79,2.38,0.21,0.00,54.64,63.88,51.89,16.63,39.23,66.28,8.96,9.31,17.24,0.0,0.0,0.00,0.0,0.0,0.0,25.59,48.54,83.53,80.24,112.43,136.01,0.0,0.0,0.50,0.00,0.0,0.00,0.00,0.00,0.08,5,11,9,200,313,308,90,44,44,6/28/2014,7/31/2014,8/27/2014,50,30,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,712,0.00,0.00,0.00,0
69996,69996,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,372.088,258.374,279.782,77.13,68.44,78.44,335.54,227.94,263.84,0.00,0.0,0.0,0.00,0.0,0.00,77.13,44.28,78.44,143.19,82.58,138.26,142.58,141.26,125.58,0.00,4.10,0.00,362.91,268.13,342.29,0.00,24.16,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,24.16,0.00,0.21,0.0,0.0,49.54,4.10,0.00,0.00,0.0,0.0,412.68,296.39,342.29,46.41,30.29,86.53,143.94,147.01,177.73,339.11,236.16,147.74,529.48,413.48,412.01,0.00,0.00,0.00,0.00,0.00,0.00,2.5,0.0,2.48,0.0,0.0,0.0,2.50,0.00,2.48,542.18,416.58,414.54,0.0,0.0,0.00,5.05,0.0,0.05,5.14,3.09,0.00,3,1,4,626,250,397,279,250,349,6/25/2014,7/30/2014,8/29/2014,279,250,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,879,0.00,0.00,0.00,0
69997,69997,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,238.575,245.414,145.062,14.01,7.64,6.71,30.34,16.68,12.56,25.06,0.0,0.0,4.58,0.0,0.00,10.88,7.64,6.71,4.44,6.66,8.84,7.99,1.45,2.86,0.00,0.00,0.00,23.33,15.76,18.43,2.15,0.00,0.00,14.30,8.56,0.85,0.00,0.0,0.0,0.0,0.0,0.0,16.45,8.56,0.85,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,39.78,24.33,19.28,11.36,3.64,1.04,0.66,1.68,3.94,0.34,4.28,2.81,12.38,9.61,7.81,3.70,4.61,1.30,2.74,2.01,7.36,0.0,0.0,1.28,0.0,0.0,0.0,6.44,6.63,9.94,18.83,16.24,17.76,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,5,3,2,379,252,145,200,252,145,6/29/2014,7/19/2014,8/26/2014,0,0,0,6/17/2014,7/13/2014,8/14/2014,1.0,1.0,1.0,179.0,252.0,145.0,0.0,0.0,0.0,1.0,1.0,1.0,179.0,252.0,145.0,46.25,57.61,44.64,1253.47,1774.18,658.19,150.67,212.18,122.08,150.67,212.17,122.07,0.0,0.0,0.0,0,0,0,0,0,0,1,1,1,0,0,0,1.0,1.0,1.0,277,664.25,1402.96,990.97,0
69998,69998,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,168.269,42.815,167.961,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,2.21,4.31,0.96,2.68,38.71,31.69,0.43,5.78,0.00,5.33,48.81,32.66,0.00,0.00,0.00,0.00,16.28,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,16.28,0.00,8.13,65.09,33.58,0.0,0.0,0.00,0.00,0.0,0.55,2.80,0.00,0.36,2,2,2,198,50,198,198,50,198,6/19/2014,7/27/2014,8/25/2014,198,0,0,6/19/2014,NaN,8/8/2014,1.0,NaN,1.0,198.0,NaN,198.0,1.0,NaN,1.0,0.0,NaN,0.0,198.0,NaN,198.0,280.70,0.00,982.54,0.00,0.00,0.00,0.00,NaN,0.00,0.00,NaN,0.02,0.0,NaN,0.0,1,0,1,0,0,0,0,0,0,0,0,0,1.0,NaN,1.0,1876,0.00,0.00,0.00,0

In [4]:
df.describe()

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,churn_probability
count,69999.000000,69999.0,69297.0,69297.0,69297.0,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.0,67312.0,66296.0,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.0,67312.0,66296.0,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.00000,69999.000000
mean,34999.000000,109.0,0.0,0.0,0.0,283.134365,278.185912,278.858826,133.153275,133.894438,132.978257,198.874771,197.153383,196.543577,9.765435,7.014568,7.004892,14.186457,9.842191,9.771783,46.904854,46.166503,45.686109,93.238231,90.799240,91.121447,3.743179,3.777031,3.661652,1.126025,1.361052,1.420840,143.893585,140.750120,140.476486,80.619382,83.775851,83.471486,88.152110,91.538615,90.586999,1.126377,1.084062,1.057739,0.0,0.0,0.0,169.900601,176.401217,175.118852,0.845763,0.811100,0.841648,3.958619,4.976783,5.045027,0.462581,0.024425,0.033059,306.451436,310.572674,304.513065,48.043255,47.882736,47.256388,107.152439,106.489856,108.154731,12.050672,12.563665,11.716763,167.255126,166.945103,167.136761,9.476958,9.873468,9.910217,20.734858,21.685359,21.089042,2.146273,2.199395,2.075179,0.0,0.0,0.0,32.360632,33.760809,33.077030,199.710640,201.878029,198.486034,0.061932,0.033371,0.040392,7.394167,8.171162,8.348424,0.854063,1.019680,0.963214,7.566522,7.706667,7.224932,328.139788,322.376363,323.846355,104.569265,104.137573,107.540351,63.426949,59.294218,62.489478,2.467612,2.679989,2.652441,126.500000,126.402071,125.374925,1.865323,2.056311,2.016018,0.602288,0.623678,0.636423,192.831096,201.455940,196.815792,51.773924,51.240204,50.127506,122.171882,128.934444,135.486541,90.069931,89.115767,90.618564,86.863900,85.846074,86.348404,0.025273,0.024069,0.021013,0.079287,0.083401,0.080930,0.388863,0.441406,0.449492,0.075815,0.077730,0.081958,0.075344,0.081444,0.085487,0.916325,0.909544,0.890319,1220.639709,68.108597,65.935830,60.07674,0.101887
std,20207.115084,0.0,0.0,0.0,0.0,334.213918,344.366927,351.924315,299.963093,311.277193,311.896596,316.818355,322.482226,324.089234,57.374429,55.960985,53.408135,73.469261,58.511894,64.618388,150.971758,154.739002,153.716880,162.046699,153.852597,152.997805,13.319542,13.568110,13.009193,5.741811,7.914113,6.542202,252.034597,246.313148,245.342359,255.098355,266.693254,267.021929,255.771554,267.532089,270.032002,8.136645,8.325206,7.696853,0.0,0.0,0.0,392.046600,409.299501,410.697098,29.747486,29.220073,29.563367,15.854529,22.229842,17.708507,4.768437,1.716430,2.232547,465.502866,479.131770,477.936832,140.499757,147.761124,141.249368,168.455999,165.452459,166.223461,39.416076,43.495179,38.606895,252.576231,254.688718,249.288410,51.664472,56.137824,54.248186,80.294236,87.314510,81.534344,16.522232,16.171533,15.865403,0.0,0.0,0.0,104.381082,114.142230,108.469864,290.114823,296.771338,288.336731,0.164823,0.137322,0.148417,60.951165,63.604165,63.097570,12.149144,13.225373,11.697686,7.041452,7.050614,7.195597,404.211068,411.070120,426.181405,121.407701,120.782543,124.396750,97.954876,95.429492,101.996729,2.794610,3.073472,3.101265,109.352573,109.459266,109.648799,2.566377,2.799916,2.728246,1.279297,1.401230,1.457058,190.623115,198.346141,192.280532,212.513909,211.114667,213.101403,554.869965,554.096072,568.310234,193.600413,195.826990,189.907986,171.321203,178.067280,170.297094,0.156958,0.153269,0.143432,0.294719,0.304802,0.299254,1.494206,1.651012,1.632450,0.358905,0.383189,0.381821,0.573003,0.634547,0.680035,0.276907,0.286842,0.312501,952.426321,269.328659,267.899034,257.22681,0.302502
min,0.000000,109.0,0.0,0.0,0.0,-2258.709000,-1289.715000,-945.808000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.380000,-26.040000,-24.490000,-35.830000,-13.090000,-55.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,180.000000,0.000000,0.000000,0.00000,0.000000
25%,17499.500000,109.0,0.0,0.0,0.0,93.581000,86.714000,84.095000,7.410000,6.675000,6.410000,34.860000,32.240000,31.575000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.660000,1.650000,1.610000,9.920000,10.090000,9.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.235000,17.590000,17.237500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.780000,42.910000,38.710000,3.030000,3.260000,3.280000,17.390000,18.610000,18.940000,0.000000,0.000000,0.000000,30.630000,32.710000,32.810000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.030000,38.640000,41.340000,38.290000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,110.000000,100.000000,90.000000,30.000000,30.000000,30.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,25.000000,25.000000,25.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,82.000000,92.000000,84.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,468.000000,0.000000,0.000000,0.00000,0.000000
50%,34999.000000,109.0,0.0,0.0,0.0,197.484000,191.588000,192.234000,34.110000,32.280000,32.100000,96.480000,91.885000,91.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.910000,11.580000,11.740000,41.030000,40.170000,40.350000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,65.190000,63.430000,63.520000,0.000000,0.000000,0.000000,3.980000,3.710000,3.300000,0.000000,0.000000,0.000000,0.0,0.0,0.0,11.730000,11.260000,10.505000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.280000,141.230000,138.360000,15.740000,15.830000,16.040000,56.460000,56.930000,58.210000,0.880000,0.910000,0.930000,92.430000,92.510000,93.890000,0.000000,0.000000,0.000000,2.040000,2.060000,2.030000,0.000000,0.000000,0.000000,0.0,0.0,0.0,5.910000,5.980000,5.830000,114.780000,116.330000,114.610000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,5.000000,229.000000,220.000000,225.000000,110.000000,110.000000,98.000000,30.000000,30.000000,30.000000,1.000000,2.000000,1.000000,145.000000,145.000000,145.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,154.000000,154.000000,154.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.520000,0.420000,0.840000,11.300000,8.800000,9.090000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,868.000000,0.000000,0.000000,0.00000,0.000000
75%,52498.500000,109.0,0.0,0.0,0.0,370.791000,365.369500,369.909000,119.390000,115.837500,115.060000,232.990000,227.630000,229.345000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,40.740000,39.760000,39.895000,110.430000,107.540000,109.245000,2.060000,2.080000,2.030000,0.000000,0.000000,0.000000,167.880000,163.932500,165.615000,31.020000,31.300000,30.760000,53.745000,54.640000,52.660000,0.000000,0.000000,0.000000,0.0,0.0,0.0,146.335000,151.645000,149.015000,0.000000,0.000000,0.000000,2.400000,3.660000,4.002500,0.000000,0.000000,0.000000,374.305000,380.045000,370.895000,46.980000,45.690000,46.280000,132.020000,131.010000,134.380000,8.140000,8.230000,8.090000,208.325000,205.530000,208.060000,4.060000,4.180000,4.052500,14.960000,15.830000,15.310000,0.000000,0.000000,0.000000,0.0,0.0,0.0,26.780000,28.160000,27.615000,251.070000,249.470000,249.710000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,10.000000,9.000000,438.000000,430.000000,436.000000,120.000000,128.000000,144.000000,110.000000,110.000000,130.000000,3.000000,3.000000,3.000000,177.000000,177.000000,179.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,252.000000,252.000000,252.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,122.070000,120.860000,122.070000,122.070000,122.070000,122.070000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1813.000000,0.000000,0.000000,0.00000,0.000000
max,69998.000000,109.0,0.0,0.0,0.0,27731.088000,35145.834000,33543.624000,7376.710000,8157.780000,10752.560000,8362.360000,7043.980000,14007.340000,2850.980000,4155.830000,4169.810000,3775.110000,2812.040000,5337.040000,6431.330000,7400.660000,10752.560000,4696.830000,4557.140000,4961.330000,617.580000,815.330000,588.290000,342.860000,916.240000,351.830000,10643.380000,7674.780000,11039.910000,7366.580000,8133.660000,8014.430000,8314.760000,6622.540000,13950.040000,628.560000,465.790000,354.160000,0.0,0.0,0.0,8432.990000,8155.530000,13980.060000,5900.660000,5490.280000,5681.540000,1023.210000,2372.510000,1075.080000,800.890000,270.240000,394.930000,10674.030000,8285.640000,14043.060000,5315.590000,9324.660000,10696.230000,4450.740000,4455.830000,6274.190000,1872.340000,1983.010000,1676.580000,7454.630000,9669.910000,10830.160000,3336.380000,4708.710000,3930.240000,5647.160000,6141.880000,5512.760000,1351.110000,1136.080000,1394.890000,0.0,0.0,0.0,5712.110000,6745.760000,5658.740000,7716.140000,9699.010000,10830.380000,19.760000,13.460000,16.860000,6789.410000,5289.540000,4127.010000,1362.940000,1495.940000,1209.860000,170.000000,138.000000,138.000000,35190.000000,40335.000000,45320.000000,4010.000000,3299.000000,4449.000000,4010.000000,3100.000000,4449.000000,61.000000,54.000000,60.000000,1555.000000,1555.000000,1555.000000,42.000000,48.000000,44.000000,29.000000,34.000000,45.000000,5920.000000,4365.000000,4076.000000,10285.900000,7873.550000,11117.610000,45735.400000,28144.120000,30036.060000,5054.370000,4980.900000,3716.900000,5054.350000,4809.360000,3483.170000,1.000000,1.000000,1.000000,4.000000,5.000000,5.000000,42.000000,48.000000,44.000000,9.000000,16.000000,16.000000,29.000000,33.000000,41.000000,1.000000,1.000000,1.000000,4337.000000,12916.220000,9165.600000,11166.21000,1.000000

The columns "circle_id", "loc_og_t2o_mou", "std_og_t2o_mou", "loc_ic_t2o_mou", "std_og_t2c_mou_6", "std_og_t2c_mou_7", "std_og_t2c_mou_8", "std_ic_t2o_mou_6", "std_ic_t2o_mou_7", "std_ic_t2o_mou_8" all have either 0 as the value or the same value for the whole dataset

In [7]:
# Check for columns with missing values
pd.set_option("display.max_rows", None)
df.isna().sum()
pd.set_option("display.max_rows", 10)

id                              0
circle_id                       0
loc_og_t2o_mou                702
std_og_t2o_mou                702
loc_ic_t2o_mou                702
last_date_of_month_6            0
last_date_of_month_7          399
last_date_of_month_8          733
arpu_6                          0
arpu_7                          0
arpu_8                          0
onnet_mou_6                  2768
onnet_mou_7                  2687
onnet_mou_8                  3703
offnet_mou_6                 2768
offnet_mou_7                 2687
offnet_mou_8                 3703
roam_ic_mou_6                2768
roam_ic_mou_7                2687
roam_ic_mou_8                3703
roam_og_mou_6                2768
roam_og_mou_7                2687
roam_og_mou_8                3703
loc_og_t2t_mou_6             2768
loc_og_t2t_mou_7             2687
loc_og_t2t_mou_8             3703
loc_og_t2m_mou_6             2768
loc_og_t2m_mou_7             2687
loc_og_t2m_mou_8             3703
loc_og_t2f_mou_6             2768
loc_og_t2f_mou_7             2687
loc_og_t2f_mou_8             3703
loc_og_t2c_mou_6             2768
loc_og_t2c_mou_7             2687
loc_og_t2c_mou_8             3703
loc_og_mou_6                 2768
loc_og_mou_7                 2687
loc_og_mou_8                 3703
std_og_t2t_mou_6             2768
std_og_t2t_mou_7             2687
std_og_t2t_mou_8             3703
std_og_t2m_mou_6             2768
std_og_t2m_mou_7             2687
std_og_t2m_mou_8             3703
std_og_t2f_mou_6             2768
std_og_t2f_mou_7             2687
std_og_t2f_mou_8             3703
std_og_t2c_mou_6             2768
std_og_t2c_mou_7             2687
std_og_t2c_mou_8             3703
std_og_mou_6                 2768
std_og_mou_7                 2687
std_og_mou_8                 3703
isd_og_mou_6                 2768
isd_og_mou_7                 2687
isd_og_mou_8                 3703
spl_og_mou_6                 2768
spl_og_mou_7                 2687
spl_og_mou_8                 3703
og_others_6                  2768
og_others_7                  2687
og_others_8                  3703
total_og_mou_6                  0
total_og_mou_7                  0
total_og_mou_8                  0
loc_ic_t2t_mou_6             2768
loc_ic_t2t_mou_7             2687
loc_ic_t2t_mou_8             3703
loc_ic_t2m_mou_6             2768
loc_ic_t2m_mou_7             2687
loc_ic_t2m_mou_8             3703
loc_ic_t2f_mou_6             2768
loc_ic_t2f_mou_7             2687
loc_ic_t2f_mou_8             3703
loc_ic_mou_6                 2768
loc_ic_mou_7                 2687
loc_ic_mou_8                 3703
std_ic_t2t_mou_6             2768
std_ic_t2t_mou_7             2687
std_ic_t2t_mou_8             3703
std_ic_t2m_mou_6             2768
std_ic_t2m_mou_7             2687
std_ic_t2m_mou_8             3703
std_ic_t2f_mou_6             2768
std_ic_t2f_mou_7             2687
std_ic_t2f_mou_8             3703
std_ic_t2o_mou_6             2768
std_ic_t2o_mou_7             2687
std_ic_t2o_mou_8             3703
std_ic_mou_6                 2768
std_ic_mou_7                 2687
std_ic_mou_8                 3703
total_ic_mou_6                  0
total_ic_mou_7                  0
total_ic_mou_8                  0
spl_ic_mou_6                 2768
spl_ic_mou_7                 2687
spl_ic_mou_8                 3703
isd_ic_mou_6                 2768
isd_ic_mou_7                 2687
isd_ic_mou_8                 3703
ic_others_6                  2768
ic_others_7                  2687
ic_others_8                  3703
total_rech_num_6                0
total_rech_num_7                0
total_rech_num_8                0
total_rech_amt_6                0
total_rech_amt_7                0
total_rech_amt_8                0
max_rech_amt_6                  0
max_rech_amt_7                  0
max_rech_amt_8                  0
date_of_last_rech_6          1101
date_of_last_rech_7          1234
date_of_last_rech_8          2461
last_day_rch_amt_6              0
last_day_rch_amt_7              0
last_day_rch_amt_8              0
date_of_last_rech_data_6    52431
date_of_last_rech_data_7    52134
date_of_last_rech_data_8    51582
total_rech_data_6           52431
total_rech_data_7           52134
total_rech_data_8           51582
max_rech_data_6             52431
max_rech_data_7             52134
max_rech_data_8             51582
count_rech_2g_6             52431
count_rech_2g_7             52134
count_rech_2g_8             51582
count_rech_3g_6             52431
count_rech_3g_7             52134
count_rech_3g_8             51582
av_rech_amt_data_6          52431
av_rech_amt_data_7          52134
av_rech_amt_data_8          51582
vol_2g_mb_6                     0
vol_2g_mb_7                     0
vol_2g_mb_8                     0
vol_3g_mb_6                     0
vol_3g_mb_7                     0
vol_3g_mb_8                     0
arpu_3g_6                   52431
arpu_3g_7                   52134
arpu_3g_8                   51582
arpu_2g_6                   52431
arpu_2g_7                   52134
arpu_2g_8                   51582
night_pck_user_6            52431
night_pck_user_7            52134
night_pck_user_8            51582
monthly_2g_6                    0
monthly_2g_7                    0
monthly_2g_8                    0
sachet_2g_6                     0
sachet_2g_7                     0
sachet_2g_8                     0
monthly_3g_6                    0
monthly_3g_7                    0
monthly_3g_8                    0
sachet_3g_6                     0
sachet_3g_7                     0
sachet_3g_8                     0
fb_user_6                   52431
fb_user_7                   52134
fb_user_8                   51582
aon                             0
aug_vbc_3g                      0
jul_vbc_3g                      0
jun_vbc_3g                      0
churn_probability               0
dtype: int64

The columns "fb_user_6", "fb_user_7", "fb_user_8", "night_pck_user_6", "night_pck_user_7", "night_pck_user_8", "arpu_3g_6", "arpu_3g_7", "arpu_3g_8", "arpu_2g_6", "arpu_2g_7", "arpu_2g_8","av_rech_amt_data_8", "av_rech_amt_data_7", "av_rech_amt_data_6", "count_rech_3g_8", "count_rech_3g_7", "count_rech_3g_6", "count_rech_2g_8", "count_rech_2g_7", "count_rech_2g_6", "max_rech_data_8", "max_rech_data_7", "max_rech_data_6", "total_rech_data_8", "total_rech_data_7", "total_rech_data_6", "date_of_last_rech_data_8", "date_of_last_rech_data_7", "date_of_last_rech_data_6", "last_date_of_month_6", "last_date_of_month_7", "last_date_of_month_8", all have >51,000 missing values out of 69,999 rows

In [64]:
# List of cols to drop with more than 50% missing values and same values
cols =["circle_id","loc_og_t2o_mou","std_og_t2o_mou","loc_ic_t2o_mou","std_og_t2c_mou_6","std_og_t2c_mou_7","std_og_t2c_mou_8","std_ic_t2o_mou_6","std_ic_t2o_mou_7","std_ic_t2o_mou_8",
      "fb_user_6","fb_user_7","fb_user_8","night_pck_user_6","night_pck_user_7","night_pck_user_8","arpu_3g_6","arpu_3g_7","arpu_3g_8","arpu_2g_6","arpu_2g_7","arpu_2g_8",
      "av_rech_amt_data_8","av_rech_amt_data_7","av_rech_amt_data_6","count_rech_3g_8","count_rech_3g_7","count_rech_3g_6","count_rech_2g_8","count_rech_2g_7","count_rech_2g_6",
      "max_rech_data_8","max_rech_data_7","max_rech_data_6","total_rech_data_8","total_rech_data_7","total_rech_data_6","date_of_last_rech_data_8","date_of_last_rech_data_7","date_of_last_rech_data_6",
      "last_date_of_month_6","last_date_of_month_7","last_date_of_month_8", "id", "date_of_last_rech_6","date_of_last_rech_7","date_of_last_rech_8"]

In [65]:
df= df.drop(cols, axis=1)

In [66]:
# Impute missing values with simple imputer, method is median
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
imp_median.fit(df)
impute_data= pd.DataFrame(imp_median.transform(df))
impute_data.columns= df.columns

SimpleImputer(strategy='median')

In [85]:
# Perform feature selection using RFE
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
X2=impute_data.drop(["churn_probability"], axis =1)
y2=impute_data["churn_probability"]
rfe = RFE(estimator=DecisionTreeClassifier(max_depth= 7), n_features_to_select=1)
rfe.fit(X2, y2)

RFE(estimator=DecisionTreeClassifier(max_depth=7), n_features_to_select=1)

In [86]:
# Get the ranks of the column
rank= pd.DataFrame()

rank['column']= X2.columns
rank['rfe_rank']= rfe.ranking_

In [87]:
# Sort the ranks in ascending
rank = rank.sort_values(by= 'rfe_rank')
cols = rank["column"].tolist()
columns_best= cols[0:30] + ["churn_probability"]

In [89]:
# Get the top 30 features
df2=impute_data[columns_best]

In [67]:
from fast_ml.model_development import train_valid_test_split
# Splitting the data into Training, validation and test sets
X_train3, y_train3, X_valid3, y_valid3, X_test3, y_test3 = train_valid_test_split(impute_data, target = "churn_probability", 
                                                                            train_size=0.7, valid_size=0.2, test_size=0.1, random_state=5)

In [6]:
# Hyperparameter Tuning for Random Forest Regressor
from sklearn.model_selection import RandomizedSearchCV

# Hyperparameters:
n_estimators = [int(i) for i in np.linspace(start = 100, stop = 500, num = 10)]

max_features =['auto','sqrt']

max_depth = [int(i) for i in np.linspace(10,50, num = 5)]
max_depth.append(None)

min_samples_split = [2,5,10]

param_grid = {"n_estimators": n_estimators, "max_features": max_features, "max_depth": max_depth, 
              "min_samples_split": min_samples_split}

In [ ]:
# Defining the model
RF2 = RandomForestClassifier()

# Hyperparameter tuning using rssandomizedsearch
modelRF2 = RandomizedSearchCV(estimator=RF2, param_distributions=param_grid, n_iter=10, cv=3, verbose=100, random_state=7, n_jobs=-1)

# Fitting the model
modelRF2.fit(X_train3, y_train3)

# Getting the best parameters
modelRF2.best_params_

In [93]:
# Training using the Random Forest Regressor
import timeit
# Creating the model
modelRF = RandomForestClassifier(n_estimators=500, max_depth=15, random_state=7, class_weight="balanced")

start = timeit.default_timer()

# Fitting the model
modelRF.fit(X_train3,y_train3)

stop = timeit.default_timer()

print('Time: ', stop - start)

RandomForestClassifier(class_weight='balanced', max_depth=15, n_estimators=500,
                       random_state=7)

Time:  86.28100066600018

In [70]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# Predicting Values for the training set
predsRFTrain = modelRF.predict(X_train3)
print("Training Confusion Matrix:")
confusion_matrix(y_train3, predsRFTrain)
print("Training Accuracy:")
accuracy_score(y_train3, predsRFTrain)

# Predicting the values for validation set
predsRF = modelRF.predict(X_valid3)

# Validation error
print("\nValidation Confusion Matrix:")
confusion_matrix(y_valid3, predsRF)
# Validation error
print("\nValidation Accuracy:")
accuracy_score(y_valid3, predsRF)

# Predicting the values for the test set
predsRF2 = modelRF.predict(X_test3)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test3, predsRF2)
print("\nTest Accuracy:")
accuracy_score(y_test3, predsRF2)

Training Confusion Matrix:

array([[42922,  1047],
       [  161,  4869]])

Training Accuracy:

0.9753464356415437

Validation Confusion Matrix:

array([[12224,   342],
       [  443,   991]])

Validation Accuracy:

0.9439285714285715

Test Confusion Matrix:

array([[6127,  205],
       [ 203,  465]])

Test Accuracy:

0.9417142857142857

In [90]:
# Splitting the data into Training, validation and test sets
X_train4, y_train4, X_valid4, y_valid4, X_test4, y_test4 = train_valid_test_split(df2, target = "churn_probability", 
                                                                            train_size=0.7, valid_size=0.2, test_size=0.1, random_state=5)

In [94]:
# Training using the Random Forest Regressor
import timeit
# Creating the model
modelRF = RandomForestClassifier(n_estimators=500, max_depth=15, random_state=7, class_weight="balanced")

start = timeit.default_timer()
# Fitting the model
modelRF.fit(X_train4,y_train4)

stop = timeit.default_timer()

print('Time: ', stop - start)

RandomForestClassifier(class_weight='balanced', max_depth=15, n_estimators=500,
                       random_state=7)

Time:  49.89910429200063

In [99]:
from sklearn.metrics import classification_report
# Predicting Values for the training set
predsRFTrain = modelRF.predict(X_train4)
print("Training Confusion Matrix:")
print(confusion_matrix(y_train4, predsRFTrain))
print("Training Accuracy:")
print(classification_report(y_train4, predsRFTrain))

# Predicting the values for validation set
predsRF = modelRF.predict(X_valid4)

# Validation error
print("\nValidation Confusion Matrix:")
print(confusion_matrix(y_valid4, predsRF))
# Validation error
print("\nValidation Accuracy:")
print(classification_report(y_valid4, predsRF))

# Predicting the values for the test set
predsRF2 = modelRF.predict(X_test4)

print("\nTest Confusion Matrix:")
print(confusion_matrix(y_test4, predsRF2))
print("\nTest Accuracy:")
print(classification_report(y_test4, predsRF2))

Training Confusion Matrix:
[[42943  1026]
 [  245  4785]]
Training Accuracy:
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99     43969
         1.0       0.82      0.95      0.88      5030

    accuracy                           0.97     48999
   macro avg       0.91      0.96      0.93     48999
weighted avg       0.98      0.97      0.97     48999


Validation Confusion Matrix:
[[12207   359]
 [  440   994]]

Validation Accuracy:
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97     12566
         1.0       0.73      0.69      0.71      1434

    accuracy                           0.94     14000
   macro avg       0.85      0.83      0.84     14000
weighted avg       0.94      0.94      0.94     14000


Test Confusion Matrix:
[[6116  216]
 [ 199  469]]

Test Accuracy:
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97      6332
         1.0       0.68      0.70      0.69       668

    accuracy                           0.94      7000
   macro avg       0.83      0.83      0.83      7000
weighted avg       0.94      0.94      0.94      7000